name = "hellish"
description = "A torrent tracker"
version = "0.0.0"

authors = ["Ekaterina Vaartis"]
maintainers = ["Ekaterina Vaartis <vaartis@kotobank.ch>"]
maintainers-logins = ["vaartis"]

executables = ["hellish"]

[[depends-on]]  # Added by alr
aws = "^21.0.0"  # Added by alr

[[actions]]
type = "pre-build"
command = ["mkdir", "-p", "obj/md4c/"]

[[actions]]
type = "pre-build"
command = ["cmake", "-B", "obj/md4c/", "deps/md4c", "-DCMAKE_BUILD_TYPE=Debug", "-DBUILD_SHARED_LIBS=OFF"]

[[actions]]
type = "pre-build"
command = ["make", "-Cobj/md4c/", "md4c", "md4c-html"]